### PR TITLE
Use pubDate as topic timestamp

### PR DESCRIPTION
**Pull request by communiteq**
I was going to add tests but I found that none of the fixtures were actually using RSS 2.0, all of them are Atom, using `published` instead of `pubDate`

Now the functionality uses `published` as a fallback but of course it would be better to have some RSS 2.0 test files as well. 
However that would be quite a lot of work for such a small change. So LMK what you think.

### CODE REVIEW

**Review by ZogStriP — APPROVED** [review]
LGTM, any chances you could also add a spec?

**Comment by communiteq** [comment]
Synced with the recent changes on main
Added a spec

**Comment by nattsw** [comment]
@communiteq could you lint as well please?

```
bundle exec stree write 
```

and you have two files failing lint

```
[warn] app/jobs/jobs/discourse_rss_polling/poll_feed.rb
[warn] spec/jobs/poll_feed_spec.rb
```

**Comment by communiteq** [comment]
@nattsw sorry for the late response. Done

**Comment by ZogStriP** [comment]
Thanks @communiteq 👍

**Pull request merged**
